name: Reviews Backfill

on:
  workflow_dispatch: {}
  schedule:
    # Каждый понедельник в 06:00 UTC (03:00 America/Sao_Paulo)
    - cron: "0 6 * * 1"

jobs:
  backfill-reviews:
    runs-on: ubuntu-latest

    env:
      # Прокидываем секреты в env, чтобы их читал агент
      DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
      SHEETS_HISTORY_ID: ${{ secrets.SHEETS_HISTORY_ID }}
      GOOGLE_SERVICE_ACCOUNT_JSON_CONTENT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_CONTENT }}

      # Чтобы импорты вида `from text_analytics_core import ...`
      # и `from reviews_backfill_agent import ...` работали без пакета
      PYTHONPATH: .

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # xlrd нужен для .xls, иногда не всегда в requirements — дублируем на всякий
          pip install xlrd

      - name: Run reviews backfill agent
        run: |
          python reviews_backfill_agent.py
