name: Surveys Weekly Report

on:
  # расписание: каждый понедельник 12:10 по МСК (UTC+3 → 09:10 UTC)
  schedule:
    - cron: "10 9 * * 1"
  # запуск вручную из Actions
  workflow_dispatch: {}

concurrency:
  group: surveys-weekly
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy google-api-python-client google-auth google-auth-httplib2 openpyxl matplotlib

      # декодируем сервисный ключ из base64 → sa.json и экспортируем путь
      - name: Prepare service account (from b64)
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON_B64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_B64 }}
        run: |
          set -euo pipefail
          export GOOGLE_SERVICE_ACCOUNT_JSON="$GITHUB_WORKSPACE/sa.json"
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON_B64" | base64 -d > "$GOOGLE_SERVICE_ACCOUNT_JSON"
          test -s "$GOOGLE_SERVICE_ACCOUNT_JSON"
          head -c 1 "$GOOGLE_SERVICE_ACCOUNT_JSON" | grep -q '{'
          echo "GOOGLE_SERVICE_ACCOUNT_JSON=$GOOGLE_SERVICE_ACCOUNT_JSON" >> "$GITHUB_ENV"

      # 1) бэкфилл анкет (история + все Report_*.xlsx), пишет в surveys_history
      - name: Backfill surveys history
        env:
          DRIVE_FOLDER_ID:   ${{ secrets.DRIVE_FOLDER_ID }}
          SHEETS_HISTORY_ID: ${{ secrets.SHEETS_HISTORY_ID }}
        run: |
          python -m agent.surveys_backfill_agent

      # 2) еженедельный отчёт по анкетам: берёт последний Report_*.xlsx,
      #    дописывает неделю при необходимости и шлёт письмо
      - name: Send weekly surveys report
        env:
          DRIVE_FOLDER_ID:   ${{ secrets.DRIVE_FOLDER_ID }}
          SHEETS_HISTORY_ID: ${{ secrets.SHEETS_HISTORY_ID }}
          RECIPIENTS:        ${{ secrets.RECIPIENTS }}
          SMTP_USER:         ${{ secrets.SMTP_USER }}
          SMTP_PASS:         ${{ secrets.SMTP_PASS }}
          SMTP_FROM:         ${{ secrets.SMTP_FROM }}
          # при необходимости можно переопределить:
          # SMTP_HOST:       smtp.gmail.com
          # SMTP_PORT:       587
        run: |
          python -m agent.surveys_weekly_report_agent
