name: Weekly Reviews Report

on:
  schedule:
    # Каждый понедельник 12:00 МСК (UTC+3) = 09:00 UTC
    - cron: "0 9 * * 1"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r agent/requirements.txt

      - name: Restore service account JSON from secret
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON_B64" | base64 -d > $GITHUB_WORKSPACE/sa.json
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON_B64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_B64 }}

      - name: Run weekly agent
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ github.workspace }}/sa.json
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          SHEETS_HISTORY_ID: ${{ secrets.SHEETS_HISTORY_ID }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
        run: |
          python agent/weekly_reviews_agent.py
